"""Domain models for register map and memory map specifications."""

from __future__ import annotations

from sqlalchemy import ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from dsm.models import Base, ExcelSheet


# -- GENERATED: Register (level2_* sheets) -----------------------
# *** GENERATED by: python scripts/codegen.py <excel> ***

class Register(Base):
    __tablename__ = "register"

    id: Mapped[int] = mapped_column(primary_key=True)
    type: Mapped[str | None] = mapped_column(Text)      # TYPE
    indx: Mapped[str | None] = mapped_column(Text)      # INDX
    page: Mapped[str | None] = mapped_column(Text)      # PAGE
    para: Mapped[str | None] = mapped_column(Text)      # PARA
    name: Mapped[str | None] = mapped_column(Text)      # NAME
    d7: Mapped[str | None] = mapped_column(Text)      # D7
    d6: Mapped[str | None] = mapped_column(Text)      # D6
    d5: Mapped[str | None] = mapped_column(Text)      # D5
    d4: Mapped[str | None] = mapped_column(Text)      # D4
    d3: Mapped[str | None] = mapped_column(Text)      # D3
    d2: Mapped[str | None] = mapped_column(Text)      # D2
    d1: Mapped[str | None] = mapped_column(Text)      # D1
    d0: Mapped[str | None] = mapped_column(Text)      # D0
    init: Mapped[str | None] = mapped_column(Text)      # INIT

    # Excel origin tracking
    sheet_id: Mapped[int | None] = mapped_column(ForeignKey("excel_sheet.id"))
    excel_row: Mapped[int | None]

    sheet: Mapped[ExcelSheet | None] = relationship()


REGMAP_FIELD_MAP: dict[str, str] = {
    "TYPE": "type",
    "INDX": "indx",
    "PAGE": "page",
    "PARA": "para",
    "NAME": "name",
    "D7": "d7",
    "D6": "d6",
    "D5": "d5",
    "D4": "d4",
    "D3": "d3",
    "D2": "d2",
    "D1": "d1",
    "D0": "d0",
    "INIT": "init",
}

REGMAP_FIELDS = ["type", "indx", "page", "para", "name", "d7", "d6", "d5", "d4", "d3", "d2", "d1", "d0", "init"]

# -- END GENERATED: Register --


# -- GENERATED: MemoryMapEntry (memorymap sheet) -----------------
# *** GENERATED by: python scripts/codegen.py <excel> ***

class MemoryMapEntry(Base):
    __tablename__ = "memorymap_entry"

    id: Mapped[int] = mapped_column(primary_key=True)
    baseaddr: Mapped[str | None] = mapped_column(Text)      # BASEADDR
    group: Mapped[str | None] = mapped_column(Text)      # Group
    midgroup: Mapped[str | None] = mapped_column(Text)      # midgroup
    comment: Mapped[str | None] = mapped_column(Text)      # Comment
    special: Mapped[str | None] = mapped_column(Text)      # special

    # Excel origin tracking
    sheet_id: Mapped[int | None] = mapped_column(ForeignKey("excel_sheet.id"))
    excel_row: Mapped[int | None]

    sheet: Mapped[ExcelSheet | None] = relationship()


MEMMAP_FIELD_MAP: dict[str, str] = {
    "BASEADDR": "baseaddr",
    "Group": "group",
    "midgroup": "midgroup",
    "Comment": "comment",
    "special": "special",
}

MEMMAP_FIELDS = ["baseaddr", "group", "midgroup", "comment", "special"]

# -- END GENERATED: MemoryMapEntry --


# -- Overview sheet (dict-like key-value structure) ----------------------------

class OverviewEntry(Base):
    """A key-value entry from an Overview-style sheet.

    Overview sheets are structured as sections (categories) separated by
    ``#CategoryName`` markers.  Each data row has a key (col A),
    value (col B), and optional comment (col C).

    Rows where key starts with ``#`` but also have a value are treated as
    commented-out entries (is_commented=True).
    """
    __tablename__ = "overview_entry"

    id: Mapped[int] = mapped_column(primary_key=True)
    category: Mapped[str | None] = mapped_column(Text)       # current section
    key: Mapped[str | None] = mapped_column(Text)             # key (# stripped)
    value: Mapped[str | None] = mapped_column(Text)           # value
    comment: Mapped[str | None] = mapped_column(Text)         # col C comment
    is_commented: Mapped[bool] = mapped_column(default=False) # #key with value
    is_category: Mapped[bool] = mapped_column(default=False)  # category header row

    # Excel origin tracking
    sheet_id: Mapped[int | None] = mapped_column(ForeignKey("excel_sheet.id"))
    excel_row: Mapped[int | None]

    sheet: Mapped[ExcelSheet | None] = relationship()


OVERVIEW_FIELDS = [
    "category", "key", "value", "comment", "is_commented", "is_category",
]


# -- Audit target registration -------------------------------------------------

from dsm.models import register_audit_target

register_audit_target("register", REGMAP_FIELDS)
register_audit_target("memorymap_entry", MEMMAP_FIELDS)
register_audit_target("overview_entry", ["category", "key", "value", "comment"])


# -- Domain class registry (tablename → class) --------------------------------

DOMAIN_REGISTRY: dict[str, type] = {
    "register": Register,
    "memorymap_entry": MemoryMapEntry,
    "overview_entry": OverviewEntry,
}

FIELD_MAP_REGISTRY: dict[str, dict[str, str]] = {
    "register": REGMAP_FIELD_MAP,
    "memorymap_entry": MEMMAP_FIELD_MAP,
}


# -- Default sheet configs (pattern → domain mapping) -------------------------
# import_xlsx() uses this when sheet_configs is not provided.

# Default patterns seeded into the DB on first import.
DEFAULT_SHEET_CONFIGS = [
    {"pattern": "level2_*", "domain_type": "register",
     "field_map": REGMAP_FIELD_MAP, "header_row": None},
    {"pattern": "memorymap", "domain_type": "memorymap_entry",
     "field_map": MEMMAP_FIELD_MAP, "header_row": None},
    {"pattern": "Overview", "domain_type": "overview_entry",
     "field_map": None, "header_row": None,
     "parser_func": "dsm.parsers.overview:parse_overview_entries"},
]


def seed_default_configs(session) -> None:
    """Insert default SheetConfigEntry rows if table is empty."""
    import json
    from dsm.models import SheetConfigEntry

    if session.query(SheetConfigEntry).count() > 0:
        return

    for cfg in DEFAULT_SHEET_CONFIGS:
        session.add(SheetConfigEntry(
            pattern=cfg["pattern"],
            domain_type=cfg["domain_type"],
            field_map_json=json.dumps(cfg["field_map"]) if cfg.get("field_map") else None,
            header_row=cfg["header_row"],
            parser_func_ref=cfg.get("parser_func"),
        ))
    session.flush()


def _default_sheet_configs():
    from dsm.xlsx_parser import SheetConfig

    return {
        "level2_*": SheetConfig(field_map=REGMAP_FIELD_MAP, domain_cls=Register),
        "memorymap": SheetConfig(field_map=MEMMAP_FIELD_MAP, domain_cls=MemoryMapEntry),
        "Overview": SheetConfig(domain_cls=OverviewEntry,
                                parser_func=_get_overview_parser()),
    }


def _get_overview_parser():
    from dsm.parsers.overview import parse_overview_entries
    return parse_overview_entries
