"""Integration tests for all DSM CLI commands.

Uses Click's CliRunner to invoke each command and verify basic functionality.
Tests use the regmap_sample.xlsx generated by create_regmap_sample.py.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest
from click.testing import CliRunner

from dsm.cli import main

# ── Fixtures ──────────────────────────────────────────────────────────

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "samples"
SCRIPTS_DIR = Path(__file__).resolve().parent.parent / "scripts"


@pytest.fixture(scope="session")
def sample_xlsx(tmp_path_factory) -> Path:
    """Generate sample xlsx once for the entire test session."""
    import sys
    sys.path.insert(0, str(SCRIPTS_DIR))
    from create_regmap_sample import create_regmap_xlsx

    tmp = tmp_path_factory.mktemp("cli_test")
    xlsx = create_regmap_xlsx()
    dest = tmp / "regmap_sample.xlsx"
    shutil.copy(xlsx, dest)
    return dest


@pytest.fixture
def runner():
    return CliRunner()


@pytest.fixture
def work_dir(tmp_path, sample_xlsx) -> Path:
    """Provide a clean working directory with a copy of the sample xlsx."""
    dest = tmp_path / "regmap_sample.xlsx"
    shutil.copy(sample_xlsx, dest)
    return tmp_path


# ── dsm import ────────────────────────────────────────────────────────

class TestImport:
    def test_import_creates_db(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "regmap_sample.db"

        result = runner.invoke(main, ["import", str(xlsx), "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert db.exists()
        assert "Imported" in result.output
        assert "level2_common" in result.output

    def test_import_default_db_path(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"

        result = runner.invoke(main, ["import", str(xlsx)])

        assert result.exit_code == 0, result.output
        # Default DB: same dir, same stem
        assert (work_dir / "regmap_sample.db").exists()


# ── dsm split ─────────────────────────────────────────────────────────

class TestSplit:
    def _import_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        return db

    def test_split_from_db(self, runner, work_dir):
        db = self._import_first(runner, work_dir)
        out_dir = work_dir / "split_out"

        result = runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
        ])

        assert result.exit_code == 0, result.output
        assert out_dir.exists()
        xlsx_files = list(out_dir.glob("*.xlsx"))
        assert len(xlsx_files) > 0
        assert "Split into" in result.output

    def test_split_from_xlsx(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        out_dir = work_dir / "split_out2"

        result = runner.invoke(main, [
            "split", str(xlsx), "--output-dir", str(out_dir),
        ])

        assert result.exit_code == 0, result.output
        assert len(list(out_dir.glob("*.xlsx"))) > 0

    def test_split_parallel(self, runner, work_dir):
        db = self._import_first(runner, work_dir)
        out_dir = work_dir / "split_par"

        result = runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
            "--parallel",
        ])

        assert result.exit_code == 0, result.output
        assert len(list(out_dir.glob("*.xlsx"))) > 0


# ── dsm query ─────────────────────────────────────────────────────────

class TestQuery:
    def _import_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        return db

    def test_query_sheets(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "sheets", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "level2_common" in result.output
        assert "level2_buscon" in result.output
        assert "memorymap" in result.output

    def test_query_ips(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "ips", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "SENSOR_A" in result.output
        assert "AMPLIFIER" in result.output

    def test_query_registers(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "registers", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "registers found" in result.output

    def test_query_registers_json(self, runner, work_dir):
        import json

        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, [
            "query", "registers", "--db", str(db), "--json",
        ])

        assert result.exit_code == 0, result.output
        data = json.loads(result.output.rsplit("\n", 2)[0])  # skip trailing count line
        assert len(data) > 0
        assert "name" in data[0]

    def test_query_memmap(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "memmap", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "entries found" in result.output


# ── dsm diff ──────────────────────────────────────────────────────────

class TestDiff:
    def _make_two_dbs(self, runner, work_dir) -> tuple[Path, Path]:
        """Create two DBs: original and a modified copy."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "a.db"
        db_b = work_dir / "b.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])

        # Copy and modify db_b
        shutil.copy(db_a, db_b)
        from dsm.models import init_db
        from dsm.domain_models import Register

        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            reg = session.query(Register).first()
            if reg:
                reg.init = "0xFF"
                session.commit()

        return db_a, db_b

    def test_diff_two_dbs(self, runner, work_dir):
        db_a, db_b = self._make_two_dbs(runner, work_dir)

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff.db"),
        ])

        assert result.exit_code == 0, result.output
        assert (work_dir / "diff.db").exists()
        assert "Saved to" in result.output

    def test_diff_identical(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "same.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])

        result = runner.invoke(main, [
            "diff", str(db), str(db),
            "--db", str(work_dir / "diff_same.db"),
        ])

        assert result.exit_code == 0, result.output


# ── dsm merge (stack) ─────────────────────────────────────────────────

class TestMergeStack:
    def _split_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        out_dir = work_dir / "split_out"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
        ])
        return out_dir

    def test_stack_merge(self, runner, work_dir):
        split_dir = self._split_first(runner, work_dir)
        output = work_dir / "merged.xlsx"

        result = runner.invoke(main, [
            "merge", "--input-dir", str(split_dir), "--output", str(output),
        ])

        assert result.exit_code == 0, result.output
        assert output.exists()
        assert "Merged" in result.output


# ── dsm merge --base (patch) ──────────────────────────────────────────

class TestMergePatch:
    def _setup_patch(self, runner, work_dir) -> tuple[Path, Path]:
        """Import, split, return (db_path, split_dir)."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "base.db"
        split_dir = work_dir / "split_out"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(split_dir),
        ])
        return db, split_dir

    def test_patch_merge(self, runner, work_dir):
        db, split_dir = self._setup_patch(runner, work_dir)
        output = work_dir / "patched.xlsx"

        result = runner.invoke(main, [
            "merge", "--input-dir", str(split_dir),
            "--base", str(db), "--output", str(output),
        ])

        assert result.exit_code == 0, result.output
        assert output.exists()
        assert "Patch merge" in result.output
