"""Integration tests for all DSM CLI commands.

Uses Click's CliRunner to invoke each command and verify basic functionality.
Tests use the regmap_sample.xlsx generated by create_regmap_sample.py.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest
from click.testing import CliRunner

from dsm.cli import main

# ── Fixtures ──────────────────────────────────────────────────────────

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "samples"
SCRIPTS_DIR = Path(__file__).resolve().parent.parent / "scripts"


@pytest.fixture(scope="session")
def sample_xlsx(tmp_path_factory) -> Path:
    """Generate sample xlsx once for the entire test session."""
    import sys
    sys.path.insert(0, str(SCRIPTS_DIR))
    from create_regmap_sample import create_regmap_xlsx

    tmp = tmp_path_factory.mktemp("cli_test")
    xlsx = create_regmap_xlsx()
    dest = tmp / "regmap_sample.xlsx"
    shutil.copy(xlsx, dest)
    return dest


@pytest.fixture
def runner():
    return CliRunner()


@pytest.fixture
def work_dir(tmp_path, sample_xlsx) -> Path:
    """Provide a clean working directory with a copy of the sample xlsx."""
    dest = tmp_path / "regmap_sample.xlsx"
    shutil.copy(sample_xlsx, dest)
    return tmp_path


# ── dsm import ────────────────────────────────────────────────────────

class TestImport:
    def test_import_creates_db(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "regmap_sample.db"

        result = runner.invoke(main, ["import", str(xlsx), "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert db.exists()
        assert "Imported" in result.output
        assert "level2_common" in result.output

    def test_import_default_db_path(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"

        result = runner.invoke(main, ["import", str(xlsx)])

        assert result.exit_code == 0, result.output
        # Default DB: same dir, same stem
        assert (work_dir / "regmap_sample.db").exists()


# ── dsm split ─────────────────────────────────────────────────────────

class TestSplit:
    def _import_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        return db

    def test_split_from_db(self, runner, work_dir):
        db = self._import_first(runner, work_dir)
        out_dir = work_dir / "split_out"

        result = runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
        ])

        assert result.exit_code == 0, result.output
        assert out_dir.exists()
        xlsx_files = list(out_dir.glob("*.xlsx"))
        assert len(xlsx_files) > 0
        assert "Split into" in result.output

    def test_split_from_xlsx(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        out_dir = work_dir / "split_out2"

        result = runner.invoke(main, [
            "split", str(xlsx), "--output-dir", str(out_dir),
        ])

        assert result.exit_code == 0, result.output
        assert len(list(out_dir.glob("*.xlsx"))) > 0

    def test_split_parallel(self, runner, work_dir):
        db = self._import_first(runner, work_dir)
        out_dir = work_dir / "split_par"

        result = runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
            "--parallel",
        ])

        assert result.exit_code == 0, result.output
        assert len(list(out_dir.glob("*.xlsx"))) > 0


# ── dsm query ─────────────────────────────────────────────────────────

class TestQuery:
    def _import_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        return db

    def test_query_sheets(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "sheets", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "level2_common" in result.output
        assert "level2_buscon" in result.output
        assert "memorymap" in result.output

    def test_query_ips(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "ips", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "SENSOR_A" in result.output
        assert "AMPLIFIER" in result.output

    def test_query_registers(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "registers", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "registers found" in result.output

    def test_query_registers_json(self, runner, work_dir):
        import json

        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, [
            "query", "registers", "--db", str(db), "--json",
        ])

        assert result.exit_code == 0, result.output
        data = json.loads(result.output.rsplit("\n", 2)[0])  # skip trailing count line
        assert len(data) > 0
        assert "name" in data[0]

    def test_query_memmap(self, runner, work_dir):
        db = self._import_first(runner, work_dir)

        result = runner.invoke(main, ["query", "memmap", "--db", str(db)])

        assert result.exit_code == 0, result.output
        assert "entries found" in result.output


# ── dsm diff ──────────────────────────────────────────────────────────

class TestDiff:
    def _make_two_dbs(self, runner, work_dir) -> tuple[Path, Path]:
        """Create two DBs: original and a modified copy."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "a.db"
        db_b = work_dir / "b.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])

        # Copy and modify db_b
        shutil.copy(db_a, db_b)
        from dsm.models import init_db
        from dsm.domain_models import Register

        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            reg = session.query(Register).first()
            if reg:
                reg.init = "0xFF"
                session.commit()

        return db_a, db_b

    def test_diff_two_dbs(self, runner, work_dir):
        """Default diff (cells) detects domain model changes at cell level."""
        db_a, db_b = self._make_two_dbs(runner, work_dir)

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff.db"),
        ])

        assert result.exit_code == 0, result.output
        assert (work_dir / "diff.db").exists()
        assert "Diff DB saved to" in result.output

    def test_diff_identical(self, runner, work_dir):
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "same.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])

        result = runner.invoke(main, [
            "diff", str(db), str(db),
            "--db", str(work_dir / "diff_same.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "No differences found" in result.output

    def test_diff_domain(self, runner, work_dir):
        """--domain flag enables domain-level diff."""
        db_a, db_b = self._make_two_dbs(runner, work_dir)

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--domain",
            "--db", str(work_dir / "diff_domain.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "registers" in result.output or "Summary" in result.output

    def test_diff_cells_default(self, runner, work_dir):
        """Default diff includes cell-level comparison."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "ca.db"
        db_b = work_dir / "cb.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])
        shutil.copy(db_a, db_b)

        # Modify an ExcelCell in db_b so cell-level diff detects it
        from dsm.models import ExcelCell as EC, init_db
        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            cell = session.query(EC).filter(EC.raw_value.isnot(None)).first()
            cell.raw_value = "__CHANGED__"
            session.commit()

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff_cells.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "cells" in result.output or "Summary" in result.output
        assert (work_dir / "diff_cells.db").exists()

        # Verify diff_cell table has rows
        from dsm.diff import init_diff_db, DiffCell
        DiffSession = init_diff_db(f"sqlite:///{work_dir / 'diff_cells.db'}")
        with DiffSession() as session:
            count = session.query(DiffCell).count()
            assert count > 0

    def test_diff_cells_style(self, runner, work_dir):
        """Test --style flag detects style changes."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "sa.db"
        db_b = work_dir / "sb.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])
        shutil.copy(db_a, db_b)

        # Modify style in db_b
        from dsm.models import ExcelCell as EC, init_db
        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            cell = session.query(EC).filter(EC.style.isnot(None)).first()
            if cell:
                cell.style = {"bg_color": "FF0000"}
                session.commit()

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--style",
            "--db", str(work_dir / "diff_style.db"),
        ])

        assert result.exit_code == 0, result.output
        assert (work_dir / "diff_style.db").exists()

    def test_diff_cells_comment(self, runner, work_dir):
        """--comment flag detects comment-only changes."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "cma.db"
        db_b = work_dir / "cmb.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])
        shutil.copy(db_a, db_b)

        # Modify a comment in db_b
        from dsm.models import ExcelCell as EC, init_db
        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            cell = session.query(EC).filter(EC.raw_value.isnot(None)).first()
            cell.comment = "NEW_COMMENT"
            session.commit()

        # Without --comment: should NOT detect comment-only change
        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff_no_comment.db"),
        ])
        assert result.exit_code == 0, result.output
        assert "No differences found" in result.output

        # With --comment: should detect comment change
        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--comment",
            "--db", str(work_dir / "diff_comment.db"),
        ])
        assert result.exit_code == 0, result.output
        assert "cells" in result.output or "Summary" in result.output

    def test_diff_all_flag(self, runner, work_dir):
        """--all flag enables all comparisons (cells + domain + comment + style + merge)."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "all.db"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])

        result = runner.invoke(main, [
            "diff", str(db), str(db),
            "--all",
            "--db", str(work_dir / "diff_all.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "No differences found" in result.output

    def test_diff_no_cells(self, runner, work_dir):
        """--no-cells with --domain gives domain-only diff."""
        db_a, db_b = self._make_two_dbs(runner, work_dir)

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--domain", "--no-cells",
            "--db", str(work_dir / "diff_domain_only.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "registers" in result.output or "Summary" in result.output

    def test_diff_smart_row_insert(self, runner, work_dir):
        """Smart diff correctly identifies row insertion without cascade."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "smart_a.db"
        db_b = work_dir / "smart_b.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])
        import shutil as _sh
        _sh.copy(db_a, db_b)

        # Insert a new row in db_b by shifting existing cells down
        # and adding a new row with distinct content
        import sqlite3
        conn = sqlite3.connect(str(db_b))
        cur = conn.cursor()

        # Find first sheet_id
        sheet_id = cur.execute(
            "SELECT id FROM excel_sheet LIMIT 1"
        ).fetchone()[0]

        # Count cells to verify we have enough data
        cell_count = cur.execute(
            "SELECT COUNT(*) FROM excel_cell WHERE sheet_id = ?", (sheet_id,)
        ).fetchone()[0]
        if cell_count < 5:
            conn.close()
            pytest.skip("Not enough cells in sample")

        # Get max col at row 3 (before shifting)
        max_col = cur.execute(
            "SELECT MAX(col) FROM excel_cell WHERE sheet_id = ? AND row = 3",
            (sheet_id,)
        ).fetchone()[0] or 5

        # Shift rows >= 3 down by 1 (two-step to avoid unique constraint)
        cur.execute(
            "UPDATE excel_cell SET row = row + 10000 "
            "WHERE sheet_id = ? AND row >= 3",
            (sheet_id,),
        )
        cur.execute(
            "UPDATE excel_cell SET row = row - 9999 "
            "WHERE sheet_id = ? AND row >= 10000",
            (sheet_id,),
        )

        # Insert new row 3 with unique content
        for col in range(1, max_col + 1):
            cur.execute(
                "INSERT INTO excel_cell (sheet_id, row, col, raw_value, is_merge_origin) "
                "VALUES (?, 3, ?, ?, 0)",
                (sheet_id, col, f"INSERTED_COL{col}"),
            )
        conn.commit()
        conn.close()

        # Positional diff: should show many changes (cascade)
        result_pos = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--positional",
            "--db", str(work_dir / "diff_pos.db"),
        ])
        assert result_pos.exit_code == 0, result_pos.output

        # Smart diff (default): should show fewer changes (only the inserted row)
        result_smart = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff_smart.db"),
        ])
        assert result_smart.exit_code == 0, result_smart.output
        assert "smart" in result_smart.output.lower() or "Cells" in result_smart.output

        # Verify smart diff has fewer diffs than positional
        from dsm.diff import init_diff_db, DiffCell
        PosSession = init_diff_db(f"sqlite:///{work_dir / 'diff_pos.db'}")
        SmartSession = init_diff_db(f"sqlite:///{work_dir / 'diff_smart.db'}")
        with PosSession() as sp, SmartSession() as ss:
            pos_count = sp.query(DiffCell).count()
            smart_count = ss.query(DiffCell).count()
            # Smart should have significantly fewer diffs
            assert smart_count < pos_count, (
                f"Smart diff ({smart_count}) should have fewer diffs "
                f"than positional ({pos_count})"
            )

    def test_diff_smart_cell_modification(self, runner, work_dir):
        """Smart diff detects cell modifications within matched rows."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db_a = work_dir / "smod_a.db"
        db_b = work_dir / "smod_b.db"

        runner.invoke(main, ["import", str(xlsx), "--db", str(db_a)])
        import shutil as _sh
        _sh.copy(db_a, db_b)

        # Modify a single cell value in db_b
        from dsm.models import ExcelCell as EC, init_db
        Session = init_db(f"sqlite:///{db_b}")
        with Session() as session:
            cell = session.query(EC).filter(EC.raw_value.isnot(None)).first()
            cell.raw_value = "__SMART_MODIFIED__"
            session.commit()

        result = runner.invoke(main, [
            "diff", str(db_a), str(db_b),
            "--db", str(work_dir / "diff_smart_mod.db"),
        ])

        assert result.exit_code == 0, result.output
        assert "cells" in result.output or "Summary" in result.output


# ── dsm merge (stack) ─────────────────────────────────────────────────

class TestMergeStack:
    def _split_first(self, runner, work_dir) -> Path:
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "test.db"
        out_dir = work_dir / "split_out"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(out_dir),
        ])
        return out_dir

    def test_stack_merge(self, runner, work_dir):
        split_dir = self._split_first(runner, work_dir)
        output = work_dir / "merged.xlsx"

        result = runner.invoke(main, [
            "merge", "--input-dir", str(split_dir), "--output", str(output),
        ])

        assert result.exit_code == 0, result.output
        assert output.exists()
        assert "Merged" in result.output


# ── dsm merge --base (patch) ──────────────────────────────────────────

class TestMergePatch:
    def _setup_patch(self, runner, work_dir) -> tuple[Path, Path]:
        """Import, split, return (db_path, split_dir)."""
        xlsx = work_dir / "regmap_sample.xlsx"
        db = work_dir / "base.db"
        split_dir = work_dir / "split_out"
        runner.invoke(main, ["import", str(xlsx), "--db", str(db)])
        runner.invoke(main, [
            "split", "--db", str(db), "--output-dir", str(split_dir),
        ])
        return db, split_dir

    def test_patch_merge(self, runner, work_dir):
        db, split_dir = self._setup_patch(runner, work_dir)
        output = work_dir / "patched.xlsx"

        result = runner.invoke(main, [
            "merge", "--input-dir", str(split_dir),
            "--base", str(db), "--output", str(output),
        ])

        assert result.exit_code == 0, result.output
        assert output.exists()
        assert "Patch merge" in result.output


# ── dsm config ───────────────────────────────────────────────────────

class TestConfig:
    """Tests for dsm config subcommands."""

    def test_config_list_seeds_defaults(self, runner, work_dir):
        """config list creates defaults if DB is empty."""
        db = work_dir / "cfg_test.db"
        # Create empty DB
        from dsm.models import init_db
        init_db(f"sqlite:///{db}")

        result = runner.invoke(main, ["config", "list", "--db", str(db)])
        assert result.exit_code == 0, result.output
        assert "level2_*" in result.output
        assert "memorymap" in result.output

    def test_config_add_and_remove(self, runner, work_dir):
        """config add creates a new entry, config remove deletes it."""
        db = work_dir / "cfg_add.db"
        from dsm.models import init_db
        init_db(f"sqlite:///{db}")

        # Add
        result = runner.invoke(main, [
            "config", "add", "--db", str(db),
            "--pattern", "custom_*", "--domain", "register",
        ])
        assert result.exit_code == 0, result.output
        assert "custom_*" in result.output

        # Verify it's in list
        result = runner.invoke(main, ["config", "list", "--db", str(db)])
        assert "custom_*" in result.output

        # Remove (ID should be 1 since it's the first entry)
        # Find the ID from list output
        import re
        ids = re.findall(r"^\s*(\d+)\s+custom_\*", result.output, re.MULTILINE)
        assert ids
        config_id = ids[0]

        result = runner.invoke(main, ["config", "remove", "--db", str(db), config_id])
        assert result.exit_code == 0, result.output

    def test_config_reset(self, runner, work_dir):
        """config reset restores defaults."""
        db = work_dir / "cfg_reset.db"
        from dsm.models import init_db
        init_db(f"sqlite:///{db}")

        # Add a custom config
        runner.invoke(main, [
            "config", "add", "--db", str(db),
            "--pattern", "custom_*", "--domain", "register",
        ])

        # Reset
        result = runner.invoke(main, ["config", "reset", "--db", str(db)])
        assert result.exit_code == 0, result.output
        assert "Reset to 3 default" in result.output

        # Verify custom is gone, defaults remain
        result = runner.invoke(main, ["config", "list", "--db", str(db)])
        assert "custom_*" not in result.output
        assert "level2_*" in result.output


# ── Formula roundtrip ────────────────────────────────────────────────

class TestFormulaRoundtrip:
    """Test that ArrayFormula and DataTableFormula survive import → export."""

    def test_array_formula_stored_correctly(self, tmp_path):
        """ArrayFormula.text and ref are stored in ExcelCell columns."""
        import openpyxl
        from openpyxl.worksheet.formula import ArrayFormula

        # Create xlsx with array formula
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "formulas"
        ws["A1"] = 10
        ws["A2"] = 20
        ws["B1"] = ArrayFormula(ref="B1:B2", text="=A1:A2*2")
        xlsx_path = tmp_path / "formulas.xlsx"
        wb.save(xlsx_path)
        wb.close()

        # Import
        from dsm.models import ExcelCell, init_db
        from dsm.xlsx_parser import import_xlsx

        db_path = tmp_path / "formulas.db"
        Session = init_db(f"sqlite:///{db_path}")
        with Session() as session:
            import_xlsx(session, xlsx_path, with_formulas=True)
            session.commit()

            # Verify formula_type and formula_ref stored
            cell = (
                session.query(ExcelCell)
                .filter(ExcelCell.formula_type == "array")
                .first()
            )
            assert cell is not None, "ArrayFormula cell not found in DB"
            assert cell.formula_ref == "B1:B2"
            assert cell.raw_value == "=A1:A2*2"

    def test_array_formula_export_roundtrip(self, tmp_path):
        """ArrayFormula survives import → DB → export_from_cells."""
        import openpyxl
        from openpyxl.worksheet.formula import ArrayFormula

        # Create xlsx with array formula
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "formulas"
        ws["A1"] = 10
        ws["B1"] = ArrayFormula(ref="B1:B2", text="=A1:A2*2")
        xlsx_path = tmp_path / "formulas.xlsx"
        wb.save(xlsx_path)
        wb.close()

        # Import
        from dsm.models import ExcelSheet, init_db
        from dsm.xlsx_parser import import_xlsx
        from dsm.exporter import export_from_cells

        db_path = tmp_path / "formulas.db"
        Session = init_db(f"sqlite:///{db_path}")
        with Session() as session:
            import_xlsx(session, xlsx_path, with_formulas=True)
            session.commit()

            sheet = session.query(ExcelSheet).first()
            out_path = tmp_path / "exported.xlsx"
            export_from_cells(session, sheet.id, out_path)

        # Verify exported xlsx has ArrayFormula
        wb2 = openpyxl.load_workbook(out_path, data_only=False)
        ws2 = wb2.active
        val = ws2["B1"].value
        assert isinstance(val, ArrayFormula), f"Expected ArrayFormula, got {type(val)}"
        assert val.text == "=A1:A2*2"
        assert val.ref == "B1:B2"
        wb2.close()

    def test_diff_moved_row_detection(self, tmp_path):
        """Smart diff detects rows that moved position without content change."""
        import openpyxl

        # Create old xlsx: rows A, B, C
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "test"
        ws["A1"], ws["B1"] = "Name", "Value"
        ws["A2"], ws["B2"] = "REG_A", "10"
        ws["A3"], ws["B3"] = "REG_B", "20"
        ws["A4"], ws["B4"] = "REG_C", "30"
        old_path = tmp_path / "old.xlsx"
        wb.save(old_path)
        wb.close()

        # Create new xlsx: rows A, C, B (B and C swapped)
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "test"
        ws["A1"], ws["B1"] = "Name", "Value"
        ws["A2"], ws["B2"] = "REG_A", "10"
        ws["A3"], ws["B3"] = "REG_C", "30"
        ws["A4"], ws["B4"] = "REG_B", "20"
        new_path = tmp_path / "new.xlsx"
        wb.save(new_path)
        wb.close()

        # Import both
        from dsm.models import init_db
        from dsm.xlsx_parser import import_xlsx

        db_old = tmp_path / "old.db"
        db_new = tmp_path / "new.db"

        S1 = init_db(f"sqlite:///{db_old}")
        with S1() as s:
            import_xlsx(s, old_path)
            s.commit()

        S2 = init_db(f"sqlite:///{db_new}")
        with S2() as s:
            import_xlsx(s, new_path)
            s.commit()

        # Run smart diff
        from dsm.diff.engine import diff_databases
        result = diff_databases(db_old, db_new, smart=True)

        moved = [c for c in result.cells if c.status == "moved"]
        assert len(moved) > 0, "Should detect moved rows"

        # Verify moved cells have both old_row and new_row
        for c in moved:
            assert c.old_row is not None
            assert c.new_row is not None
            assert c.old_row != c.new_row

        # Should not have any added/removed for the swapped rows
        added = [c for c in result.cells if c.status == "added"]
        removed = [c for c in result.cells if c.status == "removed"]
        assert len(added) == 0, f"Unexpected added cells: {added}"
        assert len(removed) == 0, f"Unexpected removed cells: {removed}"

    def test_import_uses_db_config(self, runner, work_dir, sample_xlsx):
        """Import reads sheet configs from DB when available."""
        db = work_dir / "cfg_import.db"

        # Import — should auto-seed configs
        result = runner.invoke(main, ["import", str(sample_xlsx), "--db", str(db)])
        assert result.exit_code == 0, result.output

        # Verify configs were seeded
        result = runner.invoke(main, ["config", "list", "--db", str(db)])
        assert result.exit_code == 0, result.output
        assert "level2_*" in result.output
