"""Code generator: read an Excel file and generate flat domain model code.

Usage:
    # Auto mode: detect level2_* and memorymap sheets, generate all
    python scripts/codegen.py samples/regmap_sample.xlsx --auto --apply

    # Auto + schema doc
    python scripts/codegen.py samples/regmap_sample.xlsx --auto --apply \
        --schema-doc skill/dsm-skill/schema.md

    # Manual: single sheet
    python scripts/codegen.py samples/regmap_sample.xlsx --sheet level2_common

    # Apply directly to domain_models.py (replaces GENERATED section)
    python scripts/codegen.py samples/regmap_sample.xlsx --sheet level2_common --apply

Generates flat ORM class + FIELD_MAP + field list for DSM domain models.
"""

from __future__ import annotations

import fnmatch
import re
import sys
from pathlib import Path

import click
import openpyxl
from openpyxl.worksheet.worksheet import Worksheet

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_DOMAIN_MODELS_PATH = _PROJECT_ROOT / "src" / "dsm" / "domain_models.py"

# Known sheet patterns -> (prefix, tablename, sheet_label)
_AUTO_TARGETS = [
    ("level2_*", "Register", "register", "level2_* sheets"),
    ("memorymap", "MemoryMapEntry", "memorymap_entry", "memorymap sheet"),
]


# ── Header detection ──────────────────────────────────────────────


def _find_header_row(ws: Worksheet, max_scan: int = 30) -> int | None:
    """Find the first row with >= 3 non-empty string cells."""
    for row in ws.iter_rows(min_row=1, max_row=min(max_scan, ws.max_row or 1)):
        str_cells = [
            c for c in row
            if c.value is not None and isinstance(c.value, str) and c.value.strip()
        ]
        if len(str_cells) >= 3:
            return row[0].row
    return None


# ── Name conversion ───────────────────────────────────────────────


def _to_python_name(header: str) -> str:
    """Convert Excel header to a valid Python/SQL identifier.

    'Reg. Name' -> 'reg_name'
    'Reset Value' -> 'reset_value'
    'BASE_ADDRESS' -> 'base_address'
    'D7' -> 'd7'
    'TYPE' -> 'type'

    Note: unlike SRegM codegen, DSM uses Python reserved words (e.g. 'type')
    as column names directly, since SQLAlchemy handles them fine.
    """
    s = header.strip().replace(".", "")
    s = re.sub(r"[^a-zA-Z0-9]", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", s)
    return s.lower()


# ── Excel analysis ────────────────────────────────────────────────


def _analyze_excel(ws: Worksheet, header_row: int) -> dict:
    """Collect headers and sample data from an Excel sheet."""
    headers: dict[int, str] = {}
    _MAX_COL = 100
    for row in ws.iter_rows(min_row=header_row, max_row=header_row,
                            max_col=min(_MAX_COL, ws.max_column or _MAX_COL)):
        for cell in row:
            if cell.value and isinstance(cell.value, str) and cell.value.strip():
                headers[cell.column] = cell.value.strip()

    return {"headers": headers, "header_row": header_row}


# ── Code generation (flat model) ─────────────────────────────────


def _generate_flat_model(
    headers: dict[int, str],
    prefix: str = "Register",
    tablename: str | None = None,
    sheet_label: str = "level2_* sheets",
) -> str:
    """Generate ORM class + FIELD_MAP + field list for a flat domain model."""
    if tablename is None:
        tablename = _to_python_name(prefix)

    fields = [(headers[c], _to_python_name(headers[c])) for c in sorted(headers)]

    # Derive a short tag for the FIELD_MAP name
    # Register -> REGMAP, MemoryMapEntry -> MEMMAP, etc.
    tag = _field_map_tag(prefix)

    lines: list[str] = []

    # ── Marker begin
    lines.append(f"# -- GENERATED: {prefix} ({sheet_label}) " + "-" * max(0, 46 - len(prefix) - len(sheet_label)))
    lines.append(f"# *** GENERATED by: python scripts/codegen.py <excel> ***")
    lines.append("")

    # ── ORM class
    lines.append(f"class {prefix}(Base):")
    lines.append(f'    __tablename__ = "{tablename}"')
    lines.append("")
    lines.append("    id: Mapped[int] = mapped_column(primary_key=True)")
    for header_text, py_name in fields:
        lines.append(f"    {py_name}: Mapped[str | None] = mapped_column(Text)      # {header_text}")
    lines.append("")
    lines.append("    # Excel origin tracking")
    lines.append('    sheet_id: Mapped[int | None] = mapped_column(ForeignKey("excel_sheet.id"))')
    lines.append("    excel_row: Mapped[int | None]")
    lines.append("")
    lines.append("    sheet: Mapped[ExcelSheet | None] = relationship()")
    lines.append("")
    lines.append("")

    # ── FIELD_MAP
    lines.append(f"{tag}_FIELD_MAP: dict[str, str] = {{")
    for header_text, py_name in fields:
        lines.append(f'    "{header_text}": "{py_name}",')
    lines.append("}")
    lines.append("")

    # ── Field list (for diff comparison)
    field_names = ", ".join(f'"{py}"' for _, py in fields)
    lines.append(f"{tag}_FIELDS = [{field_names}]")
    lines.append("")

    # ── Marker end
    lines.append(f"# -- END GENERATED: {prefix} --")

    return "\n".join(lines)


def _field_map_tag(prefix: str) -> str:
    """Derive a short uppercase tag for naming FIELD_MAP and FIELDS.

    Register -> REGMAP
    MemoryMapEntry -> MEMMAP
    Other -> uppercase of prefix
    """
    known = {
        "Register": "REGMAP",
        "MemoryMapEntry": "MEMMAP",
    }
    return known.get(prefix, prefix.upper())


# ── Apply to domain_models.py ────────────────────────────────────


def _apply_to_domain_models(generated: str, prefix: str) -> None:
    """Replace the GENERATED section for 'prefix' in domain_models.py."""
    content = _DOMAIN_MODELS_PATH.read_text()

    begin_marker = f"# -- GENERATED: {prefix} "
    end_marker = f"# -- END GENERATED: {prefix} --"

    begin_idx = content.find(begin_marker)
    end_idx = content.find(end_marker)

    if begin_idx == -1 or end_idx == -1:
        click.echo(f"ERROR: Could not find GENERATED markers for {prefix} in {_DOMAIN_MODELS_PATH}", err=True)
        click.echo(f"  Looking for: {begin_marker!r}", err=True)
        click.echo(f"  And: {end_marker!r}", err=True)
        sys.exit(1)

    end_idx += len(end_marker)
    new_content = content[:begin_idx] + generated + content[end_idx:]
    _DOMAIN_MODELS_PATH.write_text(new_content)
    click.echo(f"Applied to: {_DOMAIN_MODELS_PATH}", err=True)


# ── Schema doc generation ────────────────────────────────────────


def _generate_full_schema_doc(
    models: list[dict],
) -> str:
    """Generate a comprehensive Markdown schema document covering all models.

    Args:
        models: list of dicts, each with:
            - prefix: class name (e.g. "Register")
            - tablename: DB table name
            - sheet_label: human description
            - headers: {col_idx: header_text}
    """
    lines: list[str] = []
    lines.append("# DSM Database Schema")
    lines.append("")
    lines.append("Auto-generated by `scripts/codegen.py --auto --schema-doc`. Do not edit manually.")
    lines.append("")

    # ── Infrastructure tables (always present)
    lines.append("## Infrastructure Tables")
    lines.append("")

    lines.append("### `excel_workbook`")
    lines.append("")
    lines.append("| Column | Type | Description |")
    lines.append("|--------|------|-------------|")
    lines.append("| `id` | INTEGER | Primary key |")
    lines.append("| `filename` | TEXT | Original file name |")
    lines.append("| `blob` | BLOB | Original file binary (for round-trip export) |")
    lines.append("")

    lines.append("### `excel_sheet`")
    lines.append("")
    lines.append("| Column | Type | Description |")
    lines.append("|--------|------|-------------|")
    lines.append("| `id` | INTEGER | Primary key |")
    lines.append("| `workbook_id` | INTEGER | FK -> `excel_workbook.id` |")
    lines.append("| `name` | TEXT | Sheet name |")
    lines.append("| `header_row` | INTEGER | Detected header row |")
    lines.append("")

    lines.append("### `excel_cell`")
    lines.append("")
    lines.append("| Column | Type | Description |")
    lines.append("|--------|------|-------------|")
    lines.append("| `id` | INTEGER | Primary key |")
    lines.append("| `sheet_id` | INTEGER | FK -> `excel_sheet.id` |")
    lines.append("| `row` | INTEGER | Row number |")
    lines.append("| `col` | INTEGER | Column number |")
    lines.append("| `raw_value` | TEXT | Cell value (or formula string) |")
    lines.append("| `cached_value` | TEXT | Calculated value (data_only mode) |")
    lines.append("| `style` | JSON | Cell style (bg_color, font, number_format, ...) |")
    lines.append("| `comment` | TEXT | Cell note/comment |")
    lines.append("")

    # ── Domain tables (from codegen analysis)
    lines.append("## Domain Tables")
    lines.append("")

    for model in models:
        prefix = model["prefix"]
        tablename = model["tablename"]
        sheet_label = model["sheet_label"]
        headers = model["headers"]
        fields = [(headers[c], _to_python_name(headers[c])) for c in sorted(headers)]

        lines.append(f"### `{tablename}` ({sheet_label})")
        lines.append("")
        lines.append("| Column | Type | Excel Header |")
        lines.append("|--------|------|-------------|")
        lines.append("| `id` | INTEGER | (primary key) |")
        for header_text, py_name in fields:
            lines.append(f"| `{py_name}` | TEXT | {header_text} |")
        lines.append("| `sheet_id` | INTEGER | FK -> `excel_sheet.id` |")
        lines.append("| `excel_row` | INTEGER | Source row in Excel |")
        lines.append("")

    # ── Overview table (handwritten, not codegen)
    lines.append("### `overview_entry` (overview sheet)")
    lines.append("")
    lines.append("| Column | Type | Description |")
    lines.append("|--------|------|-------------|")
    lines.append("| `id` | INTEGER | Primary key |")
    lines.append("| `category` | TEXT | Current section (#header) |")
    lines.append("| `key` | TEXT | Key name (# stripped) |")
    lines.append("| `value` | TEXT | Value |")
    lines.append("| `comment` | TEXT | Column C comment |")
    lines.append("| `is_commented` | BOOLEAN | #key with value (commented-out entry) |")
    lines.append("| `is_category` | BOOLEAN | Category header row |")
    lines.append("| `sheet_id` | INTEGER | FK -> `excel_sheet.id` |")
    lines.append("| `excel_row` | INTEGER | Source row in Excel |")
    lines.append("")

    # ── Example SQL Queries
    lines.append("## Example SQL Queries")
    lines.append("")
    lines.append("```sql")

    for model in models:
        tablename = model["tablename"]
        headers = model["headers"]
        fields = [(headers[c], _to_python_name(headers[c])) for c in sorted(headers)]
        cols_str = ", ".join(py for _, py in fields)

        lines.append(f"-- List all {tablename} entries")
        lines.append(f"SELECT {cols_str} FROM {tablename} ORDER BY excel_row;")
        lines.append("")

    lines.append("-- List overview entries (key-value)")
    lines.append("SELECT category, key, value, comment FROM overview_entry ORDER BY excel_row;")
    lines.append("")
    lines.append("-- Count entries per sheet")
    lines.append("SELECT s.name AS sheet, COUNT(c.id) AS cells")
    lines.append("FROM excel_sheet s LEFT JOIN excel_cell c ON c.sheet_id = s.id")
    lines.append("GROUP BY s.id;")
    lines.append("")
    lines.append("-- Search cells by value")
    lines.append("SELECT s.name, c.row, c.col, c.raw_value")
    lines.append("FROM excel_cell c JOIN excel_sheet s ON c.sheet_id = s.id")
    lines.append("WHERE c.raw_value LIKE '%search_term%';")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


# ── Auto mode ─────────────────────────────────────────────────────


def _auto_detect_sheets(wb: openpyxl.Workbook) -> list[tuple[str, str, str, str]]:
    """Find sheets matching known patterns and return (sheet_name, prefix, tablename, label).

    For patterns like level2_*, picks the first matching sheet (all share headers).
    """
    found: list[tuple[str, str, str, str]] = []
    used_patterns: set[str] = set()

    for pattern, prefix, tablename, label in _AUTO_TARGETS:
        for sheet_name in wb.sheetnames:
            if fnmatch.fnmatch(sheet_name, pattern) and pattern not in used_patterns:
                found.append((sheet_name, prefix, tablename, label))
                used_patterns.add(pattern)
                break

    return found


def _run_auto(wb: openpyxl.Workbook, apply: bool, schema_doc_path: str | None) -> None:
    """Auto mode: detect sheets, generate all models, optionally apply + schema doc."""
    targets = _auto_detect_sheets(wb)

    if not targets:
        click.echo("ERROR: No known sheet patterns (level2_*, memorymap) found.", err=True)
        click.echo(f"  Available sheets: {wb.sheetnames}", err=True)
        sys.exit(1)

    click.echo(f"Auto-detected {len(targets)} targets:", err=True)
    for sheet_name, prefix, tablename, label in targets:
        click.echo(f"  {sheet_name} -> {prefix} ({tablename})", err=True)

    schema_models: list[dict] = []

    for sheet_name, prefix, tablename, label in targets:
        ws = wb[sheet_name]
        click.echo(f"\n{'='*60}", err=True)
        click.echo(f"Processing: {sheet_name} -> {prefix}", err=True)

        header_row = _find_header_row(ws)
        if header_row is None:
            click.echo(f"  WARNING: Could not detect header row, skipping.", err=True)
            continue

        click.echo(f"  Header row: {header_row}", err=True)
        result = _analyze_excel(ws, header_row)
        headers = result["headers"]

        click.echo(f"  Columns: {len(headers)}", err=True)
        for col_idx in sorted(headers):
            click.echo(f"    [{col_idx:2d}] {headers[col_idx]:20s} -> {_to_python_name(headers[col_idx])}", err=True)

        code = _generate_flat_model(headers, prefix=prefix, tablename=tablename, sheet_label=label)

        if apply:
            _apply_to_domain_models(code, prefix)
        else:
            click.echo(code)

        schema_models.append({
            "prefix": prefix,
            "tablename": tablename,
            "sheet_label": label,
            "headers": headers,
        })

    if schema_doc_path:
        doc = _generate_full_schema_doc(schema_models)
        Path(schema_doc_path).parent.mkdir(parents=True, exist_ok=True)
        Path(schema_doc_path).write_text(doc)
        click.echo(f"\nSchema doc written to: {schema_doc_path}", err=True)


# ── CLI ───────────────────────────────────────────────────────────


@click.command()
@click.argument("xlsx_path", type=click.Path(exists=True))
@click.option("--auto", is_flag=True, help="Auto-detect level2_* and memorymap sheets")
@click.option("--sheet", default=None, help="Sheet name (default: active sheet)")
@click.option("--prefix", default="Register", help="Class name (default: Register)")
@click.option("--tablename", default=None, help="DB table name (default: prefix lowercase)")
@click.option("--sheet-label", default=None,
              help='Sheet description for comments (default: "<sheet>_* sheets")')
@click.option("--output", "-o", default=None, type=click.Path(), help="Output file (default: stdout)")
@click.option("--apply", is_flag=True, help="Apply directly to src/dsm/domain_models.py")
@click.option("--schema-doc", "schema_doc_path", default=None, type=click.Path(),
              help="Generate schema documentation as Markdown")
def main(xlsx_path: str, auto: bool, sheet: str | None, prefix: str, tablename: str | None,
         sheet_label: str | None, output: str | None, apply: bool, schema_doc_path: str | None):
    """Analyze an Excel file and generate flat domain model code."""
    path = Path(xlsx_path)
    wb = openpyxl.load_workbook(path, data_only=False)

    # ── Auto mode
    if auto:
        _run_auto(wb, apply, schema_doc_path)
        wb.close()
        return

    # ── Manual (single-sheet) mode
    ws = wb[sheet] if sheet else wb.active

    click.echo(f"Sheet: {ws.title}", err=True)

    header_row = _find_header_row(ws)
    if header_row is None:
        click.echo("ERROR: Could not detect header row.", err=True)
        sys.exit(1)

    click.echo(f"Header row: {header_row}", err=True)

    result = _analyze_excel(ws, header_row)
    headers = result["headers"]

    if sheet_label is None:
        # Derive from sheet name: "level2_common" -> "level2_* sheets"
        parts = ws.title.split("_", 1)
        if len(parts) == 2:
            sheet_label = f"{parts[0]}_* sheets"
        else:
            sheet_label = f"{ws.title} sheet"

    # Show all headers
    click.echo(f"\n── Headers ({len(headers)} columns) ──", err=True)
    for col_idx in sorted(headers):
        py_name = _to_python_name(headers[col_idx])
        click.echo(f"  [{col_idx:2d}] {headers[col_idx]:20s} -> {py_name}", err=True)

    # Sample data
    click.echo(f"\n── Sample data (first 5 rows) ──", err=True)
    sorted_cols = sorted(headers)
    for row in ws.iter_rows(min_row=header_row + 1,
                            max_row=min(header_row + 5, ws.max_row or header_row),
                            max_col=max(sorted_cols) if sorted_cols else 1):
        cell_map = {c.column: c for c in row}
        vals = []
        for col_idx in sorted_cols:
            cell = cell_map.get(col_idx)
            v = str(cell.value).strip() if cell and cell.value is not None else ""
            vals.append(v[:15].ljust(15))
        row_num = row[0].row if row else "?"
        click.echo(f"  row {row_num}: {'| '.join(vals)}", err=True)

    wb.close()

    # Generate code
    code = _generate_flat_model(
        headers,
        prefix=prefix,
        tablename=tablename,
        sheet_label=sheet_label,
    )

    if apply:
        _apply_to_domain_models(code, prefix)
    elif output:
        Path(output).write_text(code)
        click.echo(f"\nGenerated code written to: {output}", err=True)
    else:
        click.echo("\n" + "=" * 72, err=True)
        click.echo("GENERATED CODE:", err=True)
        click.echo("=" * 72, err=True)
        click.echo(code)

    # Generate schema doc (single-model version for manual mode)
    if schema_doc_path:
        doc = _generate_full_schema_doc([{
            "prefix": prefix,
            "tablename": tablename or _to_python_name(prefix),
            "sheet_label": sheet_label,
            "headers": headers,
        }])
        Path(schema_doc_path).parent.mkdir(parents=True, exist_ok=True)
        Path(schema_doc_path).write_text(doc)
        click.echo(f"Schema doc written to: {schema_doc_path}", err=True)


if __name__ == "__main__":
    main()
